
services:
   
   web:
        # build: ./docker/web
        contianer-name: web_contianer
        image: moaazmustafa/grad
        volumes:
          - ./:/var/www/html/
        ports:
          - 443:443
   db:
        image: mysql:latest
       
        volumes:
          - db:/var/lib/mysql/
         
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: php_project
  

   phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8080:80

        environment:
          - PMA_HOST=db
        
volumes:
  db:
